### ISSUE TITLE
Add site url to Accept / Decline links

### ISSUE THREAD

**Issue by richardnbanks** [tradesafe/woocommerce#3]
Current the Accept/Decline links are hardcoded to start from the site root. If WordPress is installed in a sub folder these links break.

**Comment by yourdesigncoza** [comment]
Relative URL's should be avoided in any dynamic environment ( eg. CMS like WP or Drupal etc.  )  :::

**Comment by richardnbanks** [comment]
This should now be resolved by the plugin rewrite.
